name = "yaeos"
version = "0.1.0"
license = "BSD"
author = "Federico E. Benelli"
maintainer = "federico.benelli@mi.unc.edu.ar"
copyright = "Copyright 2023, Federico E. Benelli"

[build]
# link = ["lapack", "openblas"]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false
