name = "yaeos"
version = "0.1.0"
license = "MPL"
author = "Federico E. Benelli"
maintainer = "federico.benelli@mi.unc.edu.ar"
copyright = "Copyright 2023, Federico E. Benelli"

[build]
link = ["lapack"]
auto-executables = true
auto-tests = true
auto-examples = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = true
source-form = "free"

[dependencies]
stdlib = "*"
test-drive = {git = "https://github.com/fortran-lang/test-drive"}
json-fortran = {git="https://github.com/jacobwilliams/json-fortran"}
nlopt-f = {git="https://github.com/grimme-lab/nlopt-f"}
PowellOpt = { git="https://github.com/jacobwilliams/PowellOpt.git" }

[[example]]
name       = "example"
source-dir = "example"
main       = "demo.f90"
