name = "yaeos"
version = "0.1.0"
license = "BSD"
author = "Federico E. Benelli"
maintainer = "federico.benelli@mi.unc.edu.ar"
copyright = "Copyright 2023, Federico E. Benelli"

[build]
link = ["lapack"]
auto-executables = true
auto-tests = true
auto-examples = false

[install]
library = true

[dependencies]
stdlib = "*"
test-drive = {git = "https://github.com/fortran-lang/test-drive"}
json-fortran = {git="https://github.com/jacobwilliams/json-fortran"}

[[example]]
name       = "benchmark"
source-dir = "example"
main       = "demo.f90"


[[example]]
name       = "adiff_new_model"
source-dir = "example"
main       = "demo.f90"