name = "yaeos"
version = "0.2.0"
license = "MPL"
author = "Federico E. Benelli"
maintainer = "federico.benelli@mi.unc.edu.ar"
copyright = "Copyright 2023, Federico E. Benelli"

[build]
link = ["lapack"]
auto-executables = true
auto-tests = true
auto-examples = false
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = true
source-form = "free"

[dependencies]
stdlib = "*"
test-drive = {git = "https://github.com/fortran-lang/test-drive"}
json-fortran = {git="https://github.com/jacobwilliams/json-fortran"}
forsus = {git="https://github.com/ipqa-research/forsus"}
nlopt-f.git = "https://github.com/grimme-lab/nlopt-f"


[[example]]
name       = "benchmarks"
source-dir = "example/extra"
main       = "demo.f90"

[[example]]
name       = "basics"
source-dir = "example/tutorials"
main       = "basics.f90"

[[example]]
name       = "saturation_points"
source-dir = "example/tutorials"
main       = "saturation_points.f90"

[[example]]
name       = "phase_envelope"
source-dir = "example/tutorials"
main       = "phase_envelope.f90"

[[example]]
name       = "new_alpha_function"
source-dir = "example/tutorials"
main       = "new_alpha_function.f90"