[build-system]
build-backend = "setuptools.build_meta"
requires = ["fpm", "meson", "ninja", "numpy", "setuptools", "wheel"]


[tool.black]
line-length = 79
target-version = ["py310"]


[tool.pytest.ini_options]
markers = [
    "marker_name: marker_description",
]