[project]
name = "yaeos"
dependencies = ["numpy"]
version = "0.1.0"
requires-python = ">=3.10"

[build-system]
build-backend = "mesonpy"
requires = [
    "meson-python>=0.15.0",
    "numpy",
    "fpm; platform_system!='Windows'",
    "ninja; platform_system!='Windows'", 
    "wheel"
]

[tool.black]
line-length = 79
target-version = ["py310"]


[tool.pytest.ini_options]
markers = [
    "marker_name: marker_description",
]
[tool.cibuildwheel]
build = "cp3{10,11,12}-manylinux_x86_64"
[tool.cibuildwheel.linux]
before-all = "yum update && yum -y install lapack-devel openblas lapack freetype"



[tool.meson-python.args]
compile = ['-vC', '-j4']
# configure = ['build-dir buildmeson']